/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaImagenes;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author jeron
 */
public class CartaVisual extends javax.swing.JPanel {

    Dimension tam = getToolkit().getScreenSize();
    public CartaVisual() {
        initComponents();

    }
    public void paintH(Graphics g){
        this.setSize(tam.width/9, tam.height/4);
        //Dimension tam = getSize();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/imagen/FondoHechizo.jpg"));
        g.drawImage(fondo.getImage(),0,0,getWidth(), getHeight(),null);
        setOpaque(false);
        super.paintComponent(g);
    
    }
    public void paintC(Graphics g){
        this.setSize(tam.width/9, tam.height/4);
        //Dimension tam = getSize();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/imagen/FondoMonstruo.jpg"));
        g.drawImage(fondo.getImage(),0,0,getWidth(), getHeight(),null);
        setOpaque(false);
        super.paintComponent(g);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 102));
        setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
