/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaImagenes;

import controlador.ControladorCartaVisual;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import juego.Juego;
import modelos.Carta;
import modelos.Jugador;

/**
 *
 * @author jeron
 */
public class CartaVisual extends javax.swing.JPanel {

    private String tipo;
    private Jugador jugador;
    private boolean enJuego;
    private Juego juego;
    private ControladorCartaVisual ccv;
    private Carta carta;

    private ArrayList<Carta> CartasEnJuego = new ArrayList<Carta>();

    public CartaVisual(Juego juego) {
        initComponents();

        this.juego = juego;

    }
   
    public void setValores(Carta carta) {
        ccv = new ControladorCartaVisual(juego);
        this.carta = carta;
        lblPoder.setText(carta.getPoder().toString());
        lblMana.setText(carta.getCoste().toString());
        jugador = carta.getJugador();
        tipo = String.valueOf(carta.getTipo());
        ccv.AgregarImagenCarta(carta.getNombre(), this);
        ccv.AgregarFondoCarta(carta.getTipo(), this);
        if(carta.isEnJuego() && carta.getTipo().equals(Carta.Tipo.criatura)){
            lblNombre.setText(carta.getNombre()+" Listo");
            lblNombre.setForeground(Color.WHITE);
        }else{
            lblNombre.setText(carta.getNombre());
            lblNombre.setForeground(Color.WHITE);
        }
        if (carta.isAtaco()) {
            lblNombre.setForeground(Color.WHITE);
            //ccv.RemueveDespuesDeAtaque(carta.getTipo(), this);
            lblNombre.setFont(new Font("Tahoma", 1, 14));
            lblNombre.setText(carta.getNombre()+"(Zzz)");
        }
        if (carta.isActiva()) {
            lblNombre.setFont(new Font("Tahoma", 1, 14));
            lblNombre.setForeground(Color.GREEN);
            
        }

    }

    public void setValores(Carta carta, boolean escondido) {
        ccv = new ControladorCartaVisual(juego);
        this.carta = carta;
        lblNombre.setVisible(false);
        lblPoder.setVisible(false);
        lblMana.setVisible(false);
        lblNombre.setText(carta.getNombre()+" Listo");
        lblPoder.setText(carta.getPoder().toString());
        lblMana.setText(carta.getCoste().toString());
        jugador = carta.getJugador();
        tipo = String.valueOf(carta.getTipo());
        ccv.AgregarFondoManoPc(this);
        if (carta.isAtaco()) {
            lblNombre.setForeground(Color.WHITE);
            //ccv.RemueveDespuesDeAtaque(carta.getTipo(), this);
            lblNombre.setFont(new Font("Tahoma", 1, 14));
            lblNombre.setText(carta.getNombre()+"(Zzz)");
            
        }
        if (carta.isActiva()) {
            lblNombre.setFont(new Font("Tahoma", 1, 14));
            lblNombre.setForeground(Color.red);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPoder = new javax.swing.JLabel();
        lblMana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPoder.setBackground(new java.awt.Color(0, 0, 51));
        lblPoder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPoder.setForeground(new java.awt.Color(204, 0, 0));
        lblPoder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMana.setBackground(new java.awt.Color(0, 0, 51));
        lblMana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMana.setForeground(new java.awt.Color(102, 255, 0));
        lblMana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMana, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lblPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        juego.cartaClickeda(carta);

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMana;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPoder;
    // End of variables declaration//GEN-END:variables
}
