/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaImagenes;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author jeron
 */
public class PanelFondoCartaC extends javax.swing.JPanel {

    /**
     * Creates new form PanelFondoCartaC
     */
    public PanelFondoCartaC() {
        initComponents();
        this.setSize(super.getHeight(), super.getWidth());
    }
    public void paint(Graphics g){
        Dimension tam = getSize();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/FondoMonstruov2.jpg"));
        g.drawImage(fondo.getImage(),0, 0, tam.width, tam.height, this);
        setOpaque(false);
        super.paintComponent(g);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
