/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jose;

import java.awt.Color;
import juego.Juego;
import modelos.Carta;

/**
 *
 * @author Usuario
 */
public class CartaVisualBasica extends javax.swing.JPanel {

    private Carta carta;
    private Juego juego;

    public CartaVisualBasica(Juego juego) {
        initComponents();
        this.juego = juego;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCoste = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPoder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("nombre");

        lblCoste.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCoste.setForeground(new java.awt.Color(51, 204, 0));
        lblCoste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoste.setText("0");

        jLabel1.setText("Poder:");

        lblPoder.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPoder.setForeground(new java.awt.Color(204, 0, 0));
        lblPoder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoder.setText("0");

        jLabel2.setText("Coste:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombre)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoder)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoste)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        juego.cartaClickeda(carta);
    }//GEN-LAST:event_formMouseClicked

    public void setValores(Carta carta) {
        this.carta = carta;
        lblNombre.setText(carta.getNombre());
        lblCoste.setText(carta.getCoste().toString());
        lblPoder.setText(carta.getPoder().toString());
        if(carta.isAtaco())
        {
            lblNombre.setForeground(Color.orange);
        }
        if (carta.isActiva()) {
            lblNombre.setForeground(Color.green);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCoste;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPoder;
    // End of variables declaration//GEN-END:variables
}
