/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import vistaImagenes.PanelPantallaPrin;

/**
 *
 * @author jeron
 */
public class InfoJuego extends javax.swing.JFrame {
    //VISTAS
    private InicioJuego iJ;
    /**
     * Creates new form InfoJuego
     */
    //CONSTRUCTOR
    public InfoJuego(InicioJuego ij) {
        this.iJ = ij;
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        AgregarFondo();
        URL url = getClass().getResource("/imagenes/NamixCardIco.png");
        ImageIcon imag = new ImageIcon(url);
        setIconImage(imag.getImage());
        
        TxtComoJugar.setText("\nComo se juega: "
                +"\n El juego consiste en derrotar al oponente acabando con su total de vida(LifePoint). Para ello contamos con diferentes tipos de criaturas y hechizos.\n"
                + "Goblins, Golemns, elfos, venenos, truenos, entre otros, requieren de maná para su invocación(identificado con color verde)\n "
                + "Un contador(también de color verde) indicará la cantidad de maná restante a usar(o no) en el turno.\n"
                + "\n Para atacar al jugador es necesario tener una criatura en el campo o poseer un hechizo, haciendo click sobre el  mismo, se verá en color rojo, y esta lista para seleccionar objetivo.\n"
                + "El paso siguiente es seleccionar el objetivo ya sea una criatura (haciendo click sobre la ella) o al oponente (haciendo click sobre la espada situada debajo de su total de vidas)\n"
                + "hasta dejar en 0 sus vidas.\n"
                + "\n Dicho esto el juego consiste en mantener el equilibrio entre un control de campo y el daño al oponente. Para sacarle el mayor provecho al mana en cada turno." );
        
    }
    //SE AGREGA FONDO A VISTA
    public void AgregarFondo(){
    
        PanelPantallaPrin fondo = new PanelPantallaPrin();
        this.add(fondo,BorderLayout.CENTER);
        fondo.repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtComoJugar = new javax.swing.JTextPane();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Como Jugar");

        TxtComoJugar.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        TxtComoJugar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtComoJugar.setEnabled(false);
        TxtComoJugar.setOpaque(false);
        jScrollPane1.setViewportView(TxtComoJugar);

        btnVolver.setBackground(new java.awt.Color(153, 153, 153));
        btnVolver.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        iJ.AgregarBotones();
        iJ.setVisible(true);
        
        this.setVisible(false);
        iJ.EliminarInfo(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TxtComoJugar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
