/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author jeron
 */
public class InfoJuego extends javax.swing.JFrame {

    /**
     * Creates new form InfoJuego
     */
    public InfoJuego() {
        initComponents();
        TxtComoJugar.setText("/nComo se juega: "
                + "/n El juego consiste en derrotar al oponente acabando con sus total de vidas(LifePoint). Para ello contamos con diferentes tipos de criaturas y hechizos."
                + "Goblins, lomens, elfos, venenos, truenos, entre otros necesitan de mana, identificado con un color verde, que se requieren para poder jugarla "
                + "un contador del mismo color te indicara cuanto te resta por usar por turno."
                + "/n Para atacar al jugador es necesario tener una criatura en el campo o poseer un hechizo, haciendo click sobre el  mismo, se vera en color rojo, y esta lista para seleccionar objetivo. "
                + "el paso sigueinte es seleccionar el objetivo ya sea a una criatura (haciendo click sobre la ella) o al oponente (haciendo click sobre la espada situada debajo de su total de vidas)"
                + "hasta dejar en 0 sus vidas."
                + "/n Dicho esto el juego consiste en manterener el equilibrio entre un control de campo y el daño al oponente. Para sacarle el mayor probecho a el mana en cada turno." );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtComoJugar = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Como Juegar");

        TxtComoJugar.setOpaque(false);
        jScrollPane1.setViewportView(TxtComoJugar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TxtComoJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
