/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorPantalla;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import modelos.InfoVisualJuego;

/**
 *
 * @author jeron
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    //Controlador
    private ControladorPantalla conp;
    //Variables
    private Dimension tam = getToolkit().getScreenSize();
    private ArrayList envioInfo = new ArrayList();

    

    public PantallaPrincipal(final ControladorPantalla conp) {
        initComponents();
        this.conp = conp;
        //SE COLOCA ICONO A VENTANA
        URL url = getClass().getResource("/imagenes/NamixCardIco.png");
        ImageIcon imag = new ImageIcon(url);
        setIconImage(imag.getImage());

        //REGistrando rezise event
        this.getRootPane().addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // This is only called when the user releases the mouse button.
                if (conp != null) {
                    conp.ActualizarPantalla(conp.getIvj());
                }
            }
        });
        
        Dimension tam = getToolkit().getScreenSize();
        this.setPreferredSize(tam);
        pack();
        this.setVisible(true);

    }
    

    //METODO PARA CARGAR LA INFORMACION RECIBIDA POR INFOVISUALJUEGO
    public void CargaInfoJuego(InfoVisualJuego inf) {

        lblLifePointsNumJ1.setText(String.valueOf(inf.getVidasJugador()));
        lblLifePointsNumJ2.setText(String.valueOf(inf.getVidasPC()));
        lblManaNumJ1.setText(String.valueOf(inf.getManaDispJugador()));
        lblManaNumJ2.setText(String.valueOf(inf.getManaDispPC()));
    }
    //METODO PARA HACER INVISIBLE LA PANTALLA
    public void invisible(){
    
        this.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTerminarT = new javax.swing.JButton();
        lblLifePointsJ1 = new javax.swing.JLabel();
        lblManaNumJ1 = new javax.swing.JLabel();
        lblManaJ1 = new javax.swing.JLabel();
        lblLifePointsNumJ1 = new javax.swing.JLabel();
        lblLifePointsJ2 = new javax.swing.JLabel();
        lblManaJ2 = new javax.swing.JLabel();
        lblLifePointsNumJ2 = new javax.swing.JLabel();
        lblManaNumJ2 = new javax.swing.JLabel();
        AtaqueALaCabeza = new javax.swing.JLabel();
        AtaqueALaCabeza1 = new javax.swing.JLabel();
        BtnRetirada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Namix Cards");
        setFocusableWindowState(false);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnTerminarT.setBackground(new java.awt.Color(153, 153, 255));
        btnTerminarT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTerminarT.setText("Paso");
        btnTerminarT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarTActionPerformed(evt);
            }
        });

        lblLifePointsJ1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLifePointsJ1.setForeground(new java.awt.Color(255, 102, 102));
        lblLifePointsJ1.setText("Life Points");

        lblManaNumJ1.setBackground(new java.awt.Color(0, 204, 51));
        lblManaNumJ1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblManaNumJ1.setForeground(new java.awt.Color(153, 255, 102));

        lblManaJ1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblManaJ1.setForeground(new java.awt.Color(153, 255, 102));
        lblManaJ1.setText("Mana");

        lblLifePointsNumJ1.setBackground(new java.awt.Color(255, 51, 51));
        lblLifePointsNumJ1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLifePointsNumJ1.setForeground(new java.awt.Color(255, 102, 102));

        lblLifePointsJ2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLifePointsJ2.setForeground(new java.awt.Color(255, 102, 102));
        lblLifePointsJ2.setText("Life Points");

        lblManaJ2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblManaJ2.setForeground(new java.awt.Color(153, 255, 102));
        lblManaJ2.setText("Mana");

        lblLifePointsNumJ2.setBackground(new java.awt.Color(255, 51, 51));
        lblLifePointsNumJ2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLifePointsNumJ2.setForeground(new java.awt.Color(255, 102, 102));

        lblManaNumJ2.setBackground(new java.awt.Color(0, 204, 51));
        lblManaNumJ2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblManaNumJ2.setForeground(new java.awt.Color(153, 255, 102));

        AtaqueALaCabeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ALaCabeza.png"))); // NOI18N
        AtaqueALaCabeza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AtaqueALaCabeza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtaqueALaCabezaMouseClicked(evt);
            }
        });

        AtaqueALaCabeza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ALaCabeza.png"))); // NOI18N
        AtaqueALaCabeza1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AtaqueALaCabeza1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtaqueALaCabeza1MouseClicked(evt);
            }
        });

        BtnRetirada.setBackground(new java.awt.Color(255, 0, 153));
        BtnRetirada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRetirada.setText("Retirada");
        BtnRetirada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetiradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLifePointsJ1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblManaJ1)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLifePointsNumJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(287, 287, 287)
                        .addComponent(lblManaNumJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLifePointsNumJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLifePointsJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManaNumJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManaJ2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnRetirada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTerminarT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AtaqueALaCabeza)
                            .addComponent(AtaqueALaCabeza1))
                        .addGap(0, 845, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManaNumJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLifePointsNumJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifePointsJ2)
                    .addComponent(lblManaJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtaqueALaCabeza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(btnTerminarT)
                .addGap(18, 18, 18)
                .addComponent(BtnRetirada)
                .addGap(10, 10, 10)
                .addComponent(AtaqueALaCabeza1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLifePointsJ1)
                            .addComponent(lblManaJ1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblManaNumJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLifePointsNumJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void btnTerminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarTActionPerformed
        conp.getJuego().terminarTurno();

    }//GEN-LAST:event_btnTerminarTActionPerformed

    private void AtaqueALaCabezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtaqueALaCabezaMouseClicked

        conp.getJuego().oponenteClickeado(conp.getJuego().getJugador2());

    }//GEN-LAST:event_AtaqueALaCabezaMouseClicked

    private void AtaqueALaCabeza1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtaqueALaCabeza1MouseClicked

        conp.getJuego().oponenteClickeado(conp.getJuego().getJugador1());

    }//GEN-LAST:event_AtaqueALaCabeza1MouseClicked

    private void BtnRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetiradaActionPerformed
        this.setVisible(false);
        InicioJuego retirada = new InicioJuego(conp.getJuego());
        retirada.setVisible(true);
    }//GEN-LAST:event_BtnRetiradaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AtaqueALaCabeza;
    private javax.swing.JLabel AtaqueALaCabeza1;
    private javax.swing.JButton BtnRetirada;
    private javax.swing.JButton btnTerminarT;
    private javax.swing.JLabel lblLifePointsJ1;
    private javax.swing.JLabel lblLifePointsJ2;
    private javax.swing.JLabel lblLifePointsNumJ1;
    private javax.swing.JLabel lblLifePointsNumJ2;
    private javax.swing.JLabel lblManaJ1;
    private javax.swing.JLabel lblManaJ2;
    private javax.swing.JLabel lblManaNumJ1;
    private javax.swing.JLabel lblManaNumJ2;
    // End of variables declaration//GEN-END:variables
}
